Initial scryer string
mozilla-l10n/scryer-android-l10n pull request #1
Opened 2018-08-27 08:35 UTC by benjamin-cheng

2018-08-27 18:20 UTC, Delphine requested changes

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Create new"
Just want to make sure "Create new" string only applies to "a new collection" because some languages will need to use feminine or masculine on "new" depending on what the noun it refers to is.

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "You won't be able to take screenshots unless this is enabled"
As mentioned in the strings doc shared with me last week, apostrophes and quotes in strings need to be "smart"/directional - not straight quotes. Please always use:
’
(Also see https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Design_for_50#Land_good_quality_strings)

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Don't ask again"
Apostrophe. Please always use:
’

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Let's load it!"
Apostrophe. Please always use:
’

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Oops! Something's wrong."
Apostrophe. Please always use:
’

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +"%1$s needs permission to access your phone's storage. Please find "
Apostrophe. Please always use:
’

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +"We're working hard to offer this feature as soon as possible. You can be "
Apostrophe. Please always use:
’

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "OK, I'm in"
Apostrophe. Please always use:
’

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Give the screenshot button a try to see what'll happen"
Apostrophe. Please always use:
’

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +#. Strings display to allow users create collection name
Nit: should be "Strings displayed" and "users to create"

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Add"
I think this could use a simple comment saying what the "Add" is for

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Next"
Would be good to have a small comment for context

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Move to"
Would be good to have a comment there to get context. 
"to" might be translated in different ways depending on what follows

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Give me a name"
Might be worth having a short comment to give context on what that's for and how it's used

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Search"
As "search" can be a noun or a verb it would be good to point that out directly in the comment as well (even though screenshot shows it, it's still good to call out in a comment)

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Unsorted"
I'd give a little context here as well for this string

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "%1$d shots"
This way of handling plurals is going to become an issue if we ever expand this app to other languages. Indonesian has no plural so we're good for now. But it would be good to reformulate this string if we're considering to expand one day.
In fact, something like replacing "%1$d shots" by "Shots: %1$d" would work better here.

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +#. Detail view: string displays on the detail view when triggering OCR
Not sure what OCR is, would be good to state and give a little bit of context on what's going on

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +#. Detail view: string displays on the detail view when triggering OCR
Also nit: should be "strings displayed"

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +#. Dialogue: strings display in the dialogues
This sounds more like a developer comment than a localization note.

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Name"
This needs more context in a localization note

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "%1$d screenshots"
Same comment about plural. A workaround could be "screenshots:  %1$d"

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "%1$d screenshots"
Workaround for plurals: "screenshots: %1$d"

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +#. Dialogue: Strings display when users skip multi-sorting panel,     Refer to
Nit: "Strings displayed"

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "%1$d remaining"
Plural comment, workaround can be "Remaining: %1$d"

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +#. Menu: strings display when triggering the overflow menu in the top-right
Nit: strings displayed

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Skip all"
I think a short comment giving context here would be helpful

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Enabled"
Needs more context from a localization note. What is enabled? Most languages need to adapt adjectives to the name's gender.

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "%1$d unsorted screenshots. Sort them now?"
Same plural issue as mentioned before.
Workaround: "Unsorted screenshots: %1$d. Sort them now?"

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +"do the magics."
I'm not entirely sure, but I believe it should be "magic" here, and not "magics"?

2018-08-27 18:20 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Later"
There should be a short comment explaining what "later" refers to here

2018-08-28 03:30 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Create new"
Yes, "create new" only applies to "a new collection." This string only appears on sorting panel and home view for users to create a new collection.

2018-08-28 03:34 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "You won't be able to take screenshots unless this is enabled"
Sorry that we made a mistake. I updated the spread sheet, but engineer didn't update the xml file. I'll update all in the xml file.

2018-08-28 03:46 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Don't ask again"
Updated all.

2018-08-28 03:46 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Let's load it!"
Updated all.

2018-08-28 03:47 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Oops! Something's wrong."
Updated all.

2018-08-28 03:47 UTC, ChenMorpheus commented on locales/templates/app.pot
> +"%1$s needs permission to access your phone's storage. Please find "
Updated all.

2018-08-28 03:47 UTC, ChenMorpheus commented on locales/templates/app.pot
> +"We're working hard to offer this feature as soon as possible. You can be "
Updated all.

2018-08-28 03:47 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "OK, I'm in"
Updated all.

2018-08-28 03:47 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Give the screenshot button a try to see what'll happen"
Updated all.

2018-08-28 03:49 UTC, ChenMorpheus commented on locales/templates/app.pot
> +#. Strings display to allow users create collection name
Updated

2018-08-28 03:52 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Add"
Added the comment: <!-- String displayed to create a new collection and add the screenshot into it -->

2018-08-28 03:58 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Next"
Added the comment: “String displayed to skip the current screenshot and move on to the next one”

2018-08-28 04:03 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Move to"
Added the comment: “String displays on the title of sorting panel and the screenshot will be categorized to a collection”

2018-08-28 04:06 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Give me a name"
Added the comment: “String displayed as a hint to ask users to type a name”

2018-08-28 04:08 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Search"
The string ID indicates it's an action. Do we still need a comment for these situations?

2018-08-28 04:09 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Unsorted"
Added the comment: “String displayed to allow users to enter a collection with all unsorted screenshots”

2018-08-28 04:11 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "%1$d shots"
@benjamin-cheng Could you check this one?

2018-08-28 08:23 UTC, benjamin-cheng commented on locales/templates/app.pot
> +msgid "You won't be able to take screenshots unless this is enabled"
@weslyhuang  @mxlius, maybe it should be listed as a retrospect item to improve our internal string management flow.

2018-08-28 09:10 UTC, benjamin-cheng commented on locales/templates/app.pot
> +msgid "%1$d screenshots"
Confirmed with @ChenMorpheus, this string can be removed.

2018-08-28 09:20 UTC, ChenMorpheus commented on locales/templates/app.pot
> +#. Detail view: string displays on the detail view when triggering OCR
Updated.

2018-08-28 09:25 UTC, ChenMorpheus commented on locales/templates/app.pot
> +#. Dialogue: strings display in the dialogues
@benjamin-cheng Could you help with this one?

2018-08-28 09:28 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Name"
Added the comment: String displayed as a tag to accomodate the name attribute, e.g. Name: shopping

2018-08-28 09:31 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "%1$d screenshots"
Please refer to  https://github.com/mozilla-l10n/scryer-android-l10n/pull/1#discussion_r213179535

2018-08-28 09:31 UTC, ChenMorpheus commented on locales/templates/app.pot
> +#. Dialogue: Strings display when users skip multi-sorting panel,     Refer to
Updated.

2018-08-28 09:32 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "%1$d remaining"
Please refer to https://github.com/mozilla-l10n/scryer-android-l10n/pull/1#discussion_r213179535

2018-08-28 09:32 UTC, ChenMorpheus commented on locales/templates/app.pot
> +#. Menu: strings display when triggering the overflow menu in the top-right
Updated.

2018-08-28 09:34 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Skip all"
Added the comment: String to allow users to skip sorting the remaining screenshots

2018-08-28 09:37 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Enabled"
Added the comment: String displayed to allow users to enable the screenshot service

2018-08-28 09:38 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "%1$d unsorted screenshots. Sort them now?"
Please refer to https://github.com/mozilla-l10n/scryer-android-l10n/pull/1#discussion_r213179535

2018-08-28 09:39 UTC, ChenMorpheus commented on locales/templates/app.pot
> +"do the magics."
This string is under reviewed by copywriter from product marketing.

2018-08-28 09:42 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Later"
Added the comment: String to allow users to dismiss the onboarding panel

2018-08-28 17:16 UTC, benjamin-cheng commented
Hi @Delphine,  according to the comments, we've updated the app.pot file. Could you please help to review? Thank you!

2018-08-28 21:41 UTC, Delphine commented on locales/templates/app.pot
> +msgid "%1$d shots"
Sounds good, thanks for the information

2018-08-28 22:02 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Create new"
Perfect then! thanks

2018-08-28 22:05 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Search"
Oh good point. I think it should be enough then

2018-08-28 22:08 UTC, Delphine commented on locales/templates/app.pot
> +#. Dialogue: strings display in the dialogues
Ok I'll wait on this to be updated, thanks

2018-08-28 22:12 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Skip all"
I realize in this case the ID was quite clear. But it's never bad to have a comment, so thanks :)

2018-08-28 22:12 UTC, Delphine commented on locales/templates/app.pot
> +"do the magics."
Ok will wait for confirmation on this as well. thanks!

2018-08-28 22:14 UTC, Delphine commented
Seems like it's almost good to go!  🤓
Just waiting for confirmation about:
* https://github.com/mozilla-l10n/scryer-android-l10n/pull/1#discussion_r213246931
and
* https://github.com/mozilla-l10n/scryer-android-l10n/pull/1#discussion_r213242555

2018-08-29 02:33 UTC, benjamin-cheng commented on locales/templates/app.pot
> +#. Dialogue: strings display in the dialogues
As discussed, @ChenMorpheus will update the comment.

2018-08-29 02:35 UTC, benjamin-cheng commented on locales/templates/app.pot
> +"do the magics."
As discussed, I will remove those strings which are not confirmed yet.

2018-08-29 03:15 UTC, ChenMorpheus commented on locales/templates/app.pot
> +#. Dialogue: strings display in the dialogues
@Delphine Updated the comment: Dialogue: strings displayed in the dialogues which inform users about a task, e.g. dialogue title, content and action

2018-08-29 06:45 UTC, benjamin-cheng commented
@Delphine, Fixed, could you please help to review? Thank you!

2018-08-29 14:47 UTC, Delphine approved these changes
I think we're good! thanks

2018-08-29 14:48 UTC, merged