Export 2019 01 08
mozilla-l10n/scryer-android-l10n pull request #8
Opened 2019-01-08 06:34 UTC by benjamin-cheng

2019-01-08 16:46 UTC, Delphine requested changes
Just a few comments.
Additionally: it seems like there already are very similar strings that exist to dialog_feedback and share ones. Is this expected that these are added, and the former ones not removed?
(for example I see: settings_list_share "share with friends" in current strings)

2019-01-08 16:46 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Share"
I think we'll need a quick localization note here to explain what is being shared

2019-01-08 16:46 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Connect"
I think we'll need a quick localization note here to explain what "connect" refers to exactly

2019-01-08 16:46 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Love Firefox ScreenshotGo?"
%1$s has been used for "Firefox ScreenshotGo", probably better to be consistent with that

2019-01-08 16:46 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Share Firefox ScreenshotGo with Friends!"
%1$s has been used for "Firefox ScreenshotGo", probably better to be consistent with that

2019-01-09 03:55 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Share"
Thanks for the suggestion. Done!

"Label used for buttons to share selected items, e.g. selected text, selected screenshot, or share the app"

2019-01-09 03:56 UTC, ChenMorpheus commented on locales/templates/app.pot
> +msgid "Connect"
Thanks for the suggestion. Done!

"String displayed to direct users to Network & internet in system Settings"

2019-01-09 04:05 UTC, ChenMorpheus commented
@Delphine 

> Just a few comments.
Additionally: it seems like there already are very similar strings that exist to dialog_feedback and share ones. Is this expected that these are added, and the former ones not removed?
(for example I see: settings_list_share "share with friends" in current strings)

Except for the two strings I replaced with the previous copy, I didn't change the other strings considering the context for users. For example, "share with friends" in settings provides enough more context. As for the "share," it follows "Share Firefox ScreenshotGo with Friends," so a verb is sufficient.

2019-01-09 07:25 UTC, benjamin-cheng commented
Hi @Delphine, we've updated the files to address your comments, could you please help to review? Thank you!

2019-01-09 19:14 UTC, Delphine approved these changes
Thanks for the updates! LGTM now :)

2019-01-09 19:14 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Share"
awesome, thank you!

2019-01-09 19:14 UTC, Delphine commented on locales/templates/app.pot
> +msgid "Connect"
thanks again! :)

2019-01-09 19:14 UTC, merged